### ISSUE TITLE
The currently installed version of Terraform (0.11.15) is not compatible with the version Terragrunt requires (>= v0.12.0)

### ISSUE THREAD

**Issue by jvanenckevort** [alpine-docker/terragrunt#11]
Could this be fixed? The terraform version is inconsistent in what terragrunt requires.

**Comment by ozbillwang** [comment]
which image did you pull? Is it latest one?

```
$ docker run -ti --rm alpine/terragrunt bash
bash-5.1# terraform version
Terraform v0.15.3
on linux_amd64
bash-5.1# terragrunt --version
terragrunt version v0.29.2
bash-5.1#
```

**Comment by jvanenckevort** [comment]
I used the latest image version at the time of writing. Since nothing changed in our codebase, I suspected the image to be faulty. Seems everything is working now.
