### ISSUE TITLE
Build requests stopped 9 days ago

### ISSUE THREAD

**Issue by bugg123** [alpine-docker/terragrunt#13]
Just wanted to let you folks know it looks like your build requests stopped.  Came looking for 1.0.2 image, thanks for all the work you've done!

**Comment by ozbillwang** [comment]
thanks for the update. recently travis asks to swith to new website from travis-ci.org to travis-ci.com. maybe something wrong, i will check

**Comment by ozbillwang** [comment]
should be the migration issue. 

the schedule is set to run daily. 

![image](https://user-images.githubusercontent.com/8954908/125758450-0464a876-ec03-4302-ad91-884e240c2f00.png)

But the latest build run 10 days ago.

![image](https://user-images.githubusercontent.com/8954908/125758624-0cd8bdd2-eb64-4aec-a6ac-8f2959b1177c.png)

I will manually trigger the build and raise a ticket to travis ci

**Comment by ozbillwang** [comment]
So it is the shit from Traivs, when the dns postfix changed from org to com, it means there is free lunch now. 

![image](https://user-images.githubusercontent.com/8954908/125760850-a161f459-0848-4896-98a0-0921e48b8fff.png)

**Comment by ozbillwang** [comment]
Ok, I will adjust the build frequency from daily to weekly. 

The new free circle will start from 17th.

**Comment by ozbillwang** [comment]
Notes have been updated in README

https://github.com/alpine-docker/terragrunt/commit/8bd3b17e72f9d2a842ecb046f94f09cf2e1a0406

**Comment by pmlk** [comment]
Also came here looking for the `1.0.2` image. It still doesn't seem to exist on docker hub. What day of the week does the weekly build run now? 😄 It doesn't seem to have been executed on the 17th, not sure if that was the plan. Is there a way to build and push this image manually just once? 😬

Thanks for your work! 🙏

**Comment by ozbillwang** [comment]
The Support team Travis CI need review my request to manually re-active the free credit, their system doesn't auto refresh the credit in next month circle. 

I am still deailing with them.

**Comment by ozbillwang** [comment]
this project is simple, so I have switched the pipeline to Circle CI with #14

you should be fine to get tag 1.0.2 now.

cc: @pmlk  @bugg123
