### ISSUE TITLE
Automation is broken for terraform 0.12

### ISSUE THREAD

**Issue by dubsgordon** [alpine-docker/terragrunt#15]
Just an FYI that it seems the automation is broken. Terraform 0.12.31 exists, but the latest alpine/terragrunt for version 12 is still 0.12.30

I don't have time to investigate this now, I fixed something up locally. If I get some time I'll try to PR a fix at a later date.

**Comment by ozbillwang** [comment]
this repo only target the latest terraform version, which already 1.0.x (GA) now.

If you want to use it, please update your terraform version to latest first
