### ISSUE TITLE
Build trigger request

### ISSUE THREAD

**Issue by smitthakkar96** [alpine-docker/terragrunt#18]
Hello there Terragrunt released a new version `v0.32.6` I am dependent on that version and I am using this image. Also builds are failing for last 2 days

**Comment by smitthakkar96** [comment]
@ozbillwang the pipeline is broken https://app.circleci.com/pipelines/github/alpine-docker/terragrunt/81/workflows/6ef1752f-4b1f-413e-a135-1c990afab3ec please check

**Comment by ozbillwang** [comment]
fixed
