### ISSUE TITLE
AWS EKS image is not getting built anymore

### ISSUE THREAD

**Issue by clushie** [alpine-docker/terragrunt#19]
Hey, this project used to provide/build a separate image which includes dependencies necessary to deploy to AWS eks.

The latest published one is [terragrunt 1.0.1-eks](https://hub.docker.com/r/alpine/terragrunt/tags/) which was published several months ago.

I guess this didn't happen on purpose, but because of an oversight when migration to circle-ci happened.

1. Do you accept merge requests to restore the behavior?
2. Should the eks image be added to the main branch instead of maintaining it on a different branch?

If yes, I would propose doing the following:

* using dockerfile builder pattern so (`FROM <image> as <base>`) and later `FROM <base> as <eks>`
* adjust the `build.sh` to build `--target <base>` and then adding a second job that does `--target <eks>`
* adjust `.circleci/config.yml` to build & publish both images

Thank you in advance

**Comment by ozbillwang** [comment]
I nearly forget the branch `eks`. 

I am thinking to merge this repo directly into https://github.com/alpine-docker/k8s 

install terragrun in `alpine/k8s`, so I only maintain one image, more than 3

* alpine/k8s
* alpine/terragrunt
* alpine/terragrunt:<tag>-eks

What's your opition?

**Comment by ozbillwang** [comment]
let me check if I can update the branch `eks`

**Comment by treksler** [comment]
any luck on this? it looks like eks variants are still not being built

**Comment by ozbillwang** [comment]
I stop supporting it with eks is because I need manage four different kubectl versions.

If we all agree to use the top 1 version (for example, currently it is 1.21.5) , then maybe I can restore the daily build 

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

<img width="727" alt="image" src="https://user-images.githubusercontent.com/8954908/160760762-b92c6886-e2b6-477a-b0d2-50ab453cd7f3.png">

**Comment by ozbillwang** [comment]
eks version is ready now

<img width="858" alt="image" src="https://user-images.githubusercontent.com/8954908/160773517-ad9f2ab2-4cfa-41f7-b18a-fa06a4fd418f.png">
