### ISSUE TITLE
Request build for docker image with Terraform version 0.11.15-oci

### ISSUE THREAD

**Issue by nayyara-samuel** [alpine-docker/terragrunt#2]
I couldn't find an image for Terraform version `0.11.15-oci` on the Docker registry. 
Can I requested to have an image with that tag built. I think the highest corresponding version of Terragrunt supported is ` 0.18.7`. 

Let me know if this is a reasonable ask. Thanks!

**Comment by ozbillwang** [comment]
both terraform and terragrunt version are upgraded, this issue doesn't make sense any more.
