### ISSUE TITLE
Provide arm64 build

### ISSUE THREAD

**Issue by kirrmann** [alpine-docker/terragrunt#21]
As alpine, terragrunt and terraform are available for arm64 it would be useful, if this docker image would also be available for arm64

**Comment by ozbillwang** [comment]
the pipeline to build for ARM is not stable. 

https://github.com/ozbillwang/multi-arch-docker-build

I have improved from a fork repo, but still not stable enable. 

Have to put this request on hold. 

if the solution works, I can adjust all repos in this group to multiple arch.

**Comment by denisa** [comment]
Have there been any progress since January 2022?

**Comment by ozbillwang** [comment]
Ok, seems its base image `hashicorp/terraform` is ready for multiple platform.

will take a try

![image](https://user-images.githubusercontent.com/8954908/233906297-47a2287c-39a2-4b04-a7b7-431a30d47f7f.png)

**Comment by ozbillwang** [comment]
@kirrmann 

it is ready, pleaes run the test from new Apple chip (M1/M2)

![image](https://user-images.githubusercontent.com/8954908/234184801-58a0c4cb-13ad-49df-8a5d-8e7740a811d2.png)

**Comment by ozbillwang** [comment]
@denisa 

run a test on ARM as well, wait for the result

**Comment by denisa** [comment]
```
$ docker run -ti --rm alpine/terragrunt terraform --version
Terraform v1.4.5
on linux_arm64
$ docker run -ti --rm  alpine/terragrunt terragrunt --version 
terragrunt version v0.45.4
```
on an m1 mac mini.

Seems to be working fine, thanks!

**Comment by ozbillwang** [comment]
Thanks for the confirmation. 

base image `hashicorp/terraform` supports four platform, but terragrunt doesn't support `linux/arm/v6` so I implement with 3 platforms. 

All good now.
