### ISSUE TITLE
Request build for Terraform `v0.13.0-beta1` (and future 0.13 betas)

### ISSUE THREAD

**Issue by percygrunwald** [alpine-docker/terragrunt#3]
Hi, firstly thank you for maintaining this repo and releasing the Terragrunt docker images. They are incredibly useful for us for deploying our Terraform code using Gitlab CI.

[Terraform `v0.13.0-beta1` was released today](https://github.com/hashicorp/terraform/releases/tag/v0.13.0-beta1) and we would like to adopt this beta straight away. To that end, it would be a massive help for us (and possibly other users) to have a build of this image using that Terraform version. I don't think the `latest` tag for this repo should point to beta releases, but it would be awesome if we could use the specific version tag to get it.

I'm not sure if the build script is set up to do this currently, happy to make a CR to adapt it if that's acceptable.

Thanks again!

**Comment by ozbillwang** [comment]
Could you wait for about half day?

the schedule job running in Travis CI (the cicd tool I am using to build this image) will run the build daily. If the release is too new, you wouldn't see it in 1 day.

If you can't see it next day, contact me.

**Comment by ficofer** [comment]
I think that the `issue` here is that terraform is not pointing **beta** releases to **latest**, thus _build.sh_ is still grabbing 0.12.26 as latest (https://travis-ci.org/github/alpine-docker/terragrunt line 201) and building this image on base of that binary and not 0.13.0-beta1

May be an improve will be for the build script to build all of them and tag correspondingly?

**Comment by ozbillwang** [comment]
beta releases are ignored.
