### ISSUE TITLE
Need a build of latest terragrunt due to segfaults

### ISSUE THREAD

**Issue by josh-thisisbud** [alpine-docker/terragrunt#32]
RE: https://github.com/gruntwork-io/terragrunt/issues/3112

I'd appreciate if you could trigger a build of the pipeline to provide us with [v0.58.5](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.58.5) which should no longer segfault during use

**Comment by ozbillwang** [comment]
it is already higher version `v0.58.7`
<img width="832" alt="image" src="https://github.com/alpine-docker/terragrunt/assets/8954908/20f2a8bd-857c-4c5c-9476-308a7e1900fa">
