### ISSUE TITLE
Default switched to OpenTofu for latest tag

### ISSUE THREAD

**Issue by Shocktrooper** [alpine-docker/terragrunt#34]
Crosspost from https://github.com/gruntwork-io/terragrunt/issues/3168

**Comment by ozbillwang** [comment]
> Crosspost from https://github.com/gruntwork-io/terragrunt/issues/3168

not realize this issue, i will set the default variable . thanks for the report

**Comment by Shocktrooper** [comment]
So while this is a solution if anyone uses this across a lot of projects like my company does this change has to potentially be made across thousands of projects which is a lot of work.  For backwards compatibility sake it would be better to leave the functionality as it was for the latest tag

**Comment by ozbillwang** [comment]
I rolled back the change.

**Comment by Shocktrooper** [comment]
Just wanted to mention in case you add the tofu binary in the future is that once a state manipulation happens with tofu it corrupts the state if switching back to terraform.  No commands can reverse this and the state file/state lock need to be edited manually in order for anything to work again
