### ISSUE TITLE
Breaking changes in Terragrunt cause image to break CI/CD

### ISSUE THREAD

**Issue by mattiassluis** [alpine-docker/terragrunt#38]
As originally brought up by #26 the current container images have tags for specific Terraform versions but not for Terragrunt versions.

Recent releases of Terragrunt (v0.67.5) made a breaking change in the default output which would break anything that tried to interpret the output of the commands (See also: https://github.com/gruntwork-io/terragrunt/issues/3367).

Because the image tags on DockerHub are not specific for Terragrunt there was no way to get an older version or other solution to fix the problem (besides fix forward or build your own image) making the use of this image unstable for CI/CD usage.

PR #27 initially fixed this by creating unique tags for each Terragrunt + Terraform version but due to other issues this change was reverted. Can we re-apply #27 and keep those changes (while the issues around OpenToFu and other refactors are being figured out)?

(Also, thank you for creating and maintaining this image, it is very much appreciated!)

**Comment by ozbillwang** [comment]
I saw the update that version 0.67.6 has fix this bug

https://github.com/gruntwork-io/terragrunt/issues/3367#issuecomment-2353391615

It seems only the latest version with 0.67.6

```
$ docker run -ti --rm alpine/terragrunt terragrunt --version
terragrunt version v0.67.5

$ docker run -ti --rm alpine/terragrunt:1.9.4 terragrunt --version
terragrunt version v0.66.8
```
What I can do now is, I will rebuild the latest `alpine/terragrunt`.

will review #27 when I have time.

**Comment by mattiassluis** [comment]
What they changed in 0.67.6 is not the default behaviour but there was a new flag that you could set `--terragrunt-forward-tf-stdout` and it didn't work as expected in some cases (so even if you wanted to have the old style output and you would set the flag it still would sometimes break the output: https://github.com/gruntwork-io/terragrunt/issues/3367#issuecomment-2316264786). With the 0.67.6 the flag would behave as expected.
A rebuild that includes the latest terragrunt version will definitely help for this specific case (using the `--terragrunt-forward-tf-stdout` flag or `TERRAGRUNT_FORWARD_TF_STDOUT=1` env) so that would be great.

Of course these kinds of changes can happen anytime which doesn't help the stability that I think is desirable with tagged containers. To quote (https://github.com/gruntwork-io/terragrunt/issues/3367#issuecomment-2316246789):

> This is not a bug. We believe that this gives better context for Terragrunt users by default, and is _an appropriate change to include in a breaking release_.
