### ISSUE TITLE
No image for terraform 1.9.6 and 1.9.7

### ISSUE THREAD

**Issue by slenky** [alpine-docker/terragrunt#39]
Hello,

The latest present image is 1.9.5, while there are already 1.9.6 and 1.9.7.
Could you please build and push it?

Thanks!

**Comment by ozbillwang** [comment]
switch the pipeline to github action (#42)

I would not fix the version of 1.9.6 and 1.9.7, latest version 1.9.8 has been built and pushed
<img width="1545" alt="image" src="https://github.com/user-attachments/assets/f1eec842-bc5c-4883-997c-b8a28675939c">
