### ISSUE TITLE
Image tags should track Terragrunt versions

### ISSUE THREAD

**Issue by billyfoss** [alpine-docker/terragrunt#4]
Currently, there are several new versions of Terragrunt released, but the TravisCI build is not updating anything, because there has not been a Terraform release in the same time frame. 

I believe the version of the terragrunt image tag should track the terragrunt version.  It also makes sense to include the Terraform version in the tag.  I will submit a PR with a proposal.

**Comment by ozbillwang** [comment]
yes, that's the design.

Terragrunt version is not that import as terraform version, to simplify the build process, I decide to use terrafrom version as this image's tag.
