### ISSUE TITLE
Request to build terragrunt image with terraform 0.13.6

### ISSUE THREAD

**Issue by macqm** [alpine-docker/terragrunt#9]
I see that 0.13.5 image was the last image from 0.13 series. 
Terraform release [0.13.6](https://github.com/hashicorp/terraform/releases/tag/v0.13.6) was out on Jan 6th.
Our remote state is not set to that version so I cannot use 0.13.5. image, but also am not ready to move to 0.14.x.

Could you provide an official build for 0.13.6?

**Comment by ozbillwang** [comment]
manually built and pushed.
